export interface card {
  name: string;
  image: string;
  rating: number;
  prosandcons: string;
}

export const cards = [
  { name: 'ACCOUNTABILITY', image: '2.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'ACCURACY', image: '3.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'ACHIEVEMENT', image: '4.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'ARTISTIC EXPRESSION', image: '5.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'AUTHENTICITY', image: '6.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'AUTHORITY', image: '7.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'AUTONOMY', image: '8.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'CELEBRATION', image: '9.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'CHALLENGE', image: '10.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'COLLABORATION', image: '11.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'COMPANY GAIN / GROWTH', image: '12.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'COMPENSATION (REMUNERATION AND INCENTIVE)', image: '13.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'COMPETITION', image: '14.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'CONNECTION TO FAMILY AND FRIENDS OUTSIDE OF WORK', image: '15.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'CONNECTION TO CLIENTS', image: '16.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'CONNECTION TO CO-WORKERS', image: '17.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'CREATIVITY', image: '18.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'DECISION MAKING AND RESPONSIBILITY', image: '19.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'DIRECT WORK WITH CLIENTS', image: '20.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'DIRECT INTERACTION WITH BROADER COMMUNITY', image: '21.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'ENTREPRENEURIAL ACUMEN', image: '22.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'EQUALITY', image: '23.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'EQUITY', image: '24.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'FAMILY CONNECTION IS SUPPORTED', image: '25.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'FLEXIBILITY', image: '26.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'FUN & LIGHT HEARTED', image: '27.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'HELPING SOCIETY', image: '28.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'HONESTY', image: '29.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'HUMAN RIGHTS', image: '30.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'HUMOUR', image: '31.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'INDEPENDENCE', image: '32.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'INFLUENCE', image: '33.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'INITIATIVE', image: '34.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'INTEGRITY', image: '35.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'JOB SECURITY', image: '36.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'LARGE GROUP INTERACTION: PUBLIC SPEAKING & ENGAGEMENT', image: '37.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'LEADERSHIP', image: '38.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'LEISURE', image: '39.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'LOYALTY', image: '40.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'PERSISTENCE', image: '41.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'POSITIVITY', image: '42.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'PRESTIGE', image: '43.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'RECOGNITION', image: '44.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'RELATIONSHIPS', image: '45.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'REWARD', image: '46.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'SELF PROMOTION', image: '47.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'SUPPORT FROM MANAGEMENT', image: '48.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'UTILISING YOUR SKILLS AND BACKGROUND', image: '49.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'VARIETY', image: '50.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] },
  { name: 'WORKING CONDITIONS', image: '51.jpg', rating: 1, prosandcons: 'Obsolete', checkedAll: [] }
];